name: End-to-end tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run start
          wait-on: 'http://localhost:5500'
          wait-on-timeout: 60 # seconds
          browser: chrome # optional; you can remove or change it